[project]
name = "text-to-speech"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "google-cloud-texttospeech>=2.23.0",
    "pydub>=0.25.1",
]

[dependency-groups]
dev = []

[tool.uv.sources]
